// pages/Portfolio.vue
<template>
    <div class="page portfolio-page bg-primary bg-opacity-5">

        <div class="page-overlay  flex-grow-1 min-h-full"></div>
  
        <!-- <div class="page-overlay flex-grow-1"></div> -->


        <div class="container  md:max-w-screen-lg 2xl:max-w-screen-2xl px-4 mx-auto ">
            <PortfolioItem class="items-center"  data-aos-duration="1000" v-for="(item, i) in projects" :key="item.id" :item="item">
            </PortfolioItem>
        </div>
    </div>
</template>


<script setup lang="ts">
import type { PortfolioItem as Project } from '@/types/PortfolioItem'

import ProjectsList from '@/data/projects.json'


import "aos/dist/aos.css";
import AOS from "aos";
const projects = ref<Project[]>()
onMounted(() => {

    AOS.init();
    projects.value = ProjectsList as Project[]
})
 

definePageMeta({
    layout: "default"
})
</script>

// app/[locale]/portfolio/page.tsx
import LightsGenerator from "@/app/components/LightsGenerator";
import React from "react";
// import projects from '@/data/projects'
import { NextPage } from "next";
import { type PortfolioItem as PortfolioItemType } from "@/types/PortfolioItem";
import ProjectDetails from "./ProjectDetails";
import PortfolioItem from "./PortfolioItem";
import { createClient } from "@/utils/supabase/server";
import BlurAppearVariant1, { MotionWrapper } from "@/components/MotionWrapper";

const page: NextPage = async (props: any) => {
  // let projectDetails: PortfolioItemType | undefined = projects.find(p => p.key === props.searchParams.project);

  const supabase = await createClient();

  let { data: projects, error } = await supabase
    .from("projects")
    .select<string, PortfolioItemType>(`* , project_skills(id,  skills(*))`);

  console.log(error);
  console.log();
  return (
    <>
      <div className="page portfolio-page  relative z-0 flex flex-col ">
        <LightsGenerator />
        <div className="page-overlay "></div>
        <div className="container lg:px-12 mx-auto py-16">
          <div className=" px-4 mx-auto space-y-24">
            {projects?.map((item) => (
              <MotionWrapper key={item.id}>
                <PortfolioItem
                  item={item}
                  className="items-center"
                  data-aos-duration={1000}
                ></PortfolioItem>
              </MotionWrapper>
            ))}
          </div>
        </div>
      </div>

      {/* <ProjectDetails project={projectDetails}></ProjectDetails> */}
    </>
  );
};
export default page;
