// app/[locale]/portfolio/PortfolioItem.tsx
"use client";
import ReadMore from "@/app/components/ReadMore";
import Image from "next/image";
import React, { useState } from "react";
import { BsGithub, BsImage } from "react-icons/bs";
import { HiOutlineExternalLink, HiPhotograph } from "react-icons/hi";
import { type PortfolioItem } from "@/types/PortfolioItem";
import { Link } from "@/i18n";
import { Button } from "@/components/ui/button";
import { BorderTrail } from "@/components/ui/BorderTrail";
import { MacbookMockUp } from "./MacbookMocUp";
import { PhotoProvider, PhotoSlider, PhotoView } from "react-photo-view";
import "react-photo-view/dist/react-photo-view.css";
export default function PortfolioItem({
  item,
}: {
  className: string;
  item: PortfolioItem;
}) {
  const [visible, setVisible] = useState(false);

  return (
    <div className="grid grid-cols-12 project gap-2 xl:gap-4" v-if="item">
      {item?.images && item.images.length && (
        <div className="image col-span-12 xl:col-span-6  file:cursor-pointer flex justify-center">
          <div className="hidden md:block">
            <MacbookMockUp>
              <div
                className="relative rounded-lg cursor-pointer h-full"
                onClick={() => setVisible(true)}
              >
                <Image
                  height={1080}
                  width={1920}
                  className="work-cover h-full w-full object-fill rounded-lg  "
                  src={item.cover_image}
                  alt={item.name}
                ></Image>
              </div>
            </MacbookMockUp>
          </div>
          <div className="md:hidden">
            <Link
              className="relative rounded-lg h-full"
              href={`/portfolio?project=${item.key}`}
              scroll={false}
            >
              <Image
                height={1080}
                width={1920}
                className="work-cover h-full w-full object-fill rounded-lg"
                src={item.cover_image}
                alt={item.name}
              ></Image>
            </Link>
          </div>

          {/* <span className="bg-primary text-white p-2 rounded-xl relative left-4 bottom-12">{item?.screenShots.length}
              <BsImage />
              
            </span> */}
        </div>
      )}
      <div className="info col-span-12 xl:col-span-6 flex flex-col justify-center px-4 gap-4">
        <h2 className="text-3xl text-primary dark:text-white text-center xl:text-6xl font-bold">
          {item.name}
        </h2>
        <span className="  dark:text-gray-400 hidden xl:block">
          {item.type}
        </span>
        <ReadMore
          className="dark:text-gray-400 text-center  md:text-lg capitalize "
          text={item?.description}
        ></ReadMore>

        <div className="tecnologies flex items-center justify-center space-y-12">
          <div className="flex mx-auto xl:mx-12 gap-8 items-center">
            {item.project_skills?.map((t) => (
              <Image
                key={t.id}
                alt={t.id.toString()}
                className="tech-icon max-w-[40px] md:max-w-[65px]"
                width={100}
                height={100}
                src={t.skills.image}
              />
            ))}
          </div>
        </div>
        <div className="flex justify-center  gap-2 xl:gap-4 ">
          {!!item.repo_url && (
            <Button
              asChild
              size={"lg"}
              className=" w-[220px] text-white bg-black hover:bg-gray-800"
            >
              <a href={item.repo_url}>
                <BsGithub />
                Github
              </a>
            </Button>
          )}
          {!!item.host_url && (
            <Button
              asChild
              size={"lg"}
              className="flex-grow xl:flex-grow-0 w-[220px]"
              variant={"outline"}
            >
              <a href={item.host_url} target="_blank">
                <HiOutlineExternalLink />
                Live Preview
              </a>
            </Button>
          )}
          <Button
            size={"lg"}
            color="secondary"
            onClick={() => setVisible(true)}
            className="flex-grow xl:flex-grow-0 w-[220px]"
            variant={"default"}
          >
            <HiPhotograph />
            Screen Shots
          </Button>
        </div>
      </div>

      <PhotoSlider
        images={item.images.map((item, i) => ({ src: item, key: item + i }))}
        visible={visible}
        onClose={() => setVisible(false)}
      />
    </div>
  );
}

// components/PortfolioItem.vue
<template>
  <div class="grid grid-cols-12 project py-12 md:py-10" v-if="item" :class="`work-item-${index}`">
    <div class="info col-span-12 lg:col-span-6 order-2 lg:order-1 flex flex-col justify-center px-4">
      <h2 class="text-5xl text-primary dark:text-white text-center lg:text-left lg:text-6xl font-bold">
        {{ item?.name }}
      </h2>

      <span class="mt-4 dark:text-gray-300 hidden lg:block">
        {{ item?.type.join(" & ") }}
      </span>

      <ReadMore class="dark:text-gray-300 text-center lg:text-left md:text-lg capitalize mt-8" :text="item?.description">
      </ReadMore>

      <p class="dark:text-gray-300 text-center lg:text-left md:text-lg capitalize mt-8" v-html="item?.workInformation">
      </p>

      <div class="tecnologies flex items-center my-6">
        <span class="dark:text-gray-300 hidden lg:block">Built With</span>
        <div class="flex mx-auto lg:mx-12 gap-12 items-center">
          <img class="tech-icon max-w-[65px] md:max-w-[100px]" v-for="img in item?.technologiesIcons" :src="iconUrl(img)" alt="" />
        </div>
      </div>
      <div class="flex items-center gap-4">
        <a :href="item.gitRepo" class="w-full lg:w-auto" v-if="item?.gitRepo">
          <button
            class="text-xl bg-black hover:bg-black/60 text-white rounded-lg w-full lg:w-48 py-4 px-4 my-4 transition-all"
            type="button">
            <icon class="text-white mr-2 text-2xl" name="codicon:github"></icon>
            Github
          </button>
        </a>
        <a :href="item?.url" v-if="item?.url"
          class="w-full text-center border px-4 hover:bg-primary hover:bg-opacity-20 text-primary border-primary rounded-lg lg:w-48 py-4 my-4 transition-all">
          Live Preview
          <icon class="text-2xl" name="tabler:external-link"></icon>
        </a>
        <span v-else-if="!item?.gitRepo" class="text-gray-400 text-sm">This Project is a Private Dashboard 😅</span>
      </div>
    </div>

    <div v-if="item?.screenShots && item.screenShots.length"
      class="image col-span-12 lg:col-span-6 order-1 lg:order-2 cursor-pointer" @click="$emit('onDetails')">
      <NuxtImg height="1080" width="1920" class="work-cover h-auto md:h-[400px] w-full object-contain lg:object-cover"
        preload quality="0.2" placeholder="https://placehold.co/750x400/161A29/546192?text=Loading..."
        v-if="item?.screenShots[0]" :src="useDriveResolver(item?.screenShots[0])"
        :class="`rounded-3xl border-4 border-seconadry dark:border-text shadow-lg `" />

      <span class="bg-primary text-white p-2 rounded-xl relative left-4 bottom-12">{{ item?.screenShots.length }}
        <icon name="clarity:image-gallery-solid" />
      </span>
    </div>




  </div>
</template>

<script lang="ts" setup>
import type { PortfolioItem } from "@/types/PortfolioItem";
import { PropType } from "vue";
import gsap from 'gsap'
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";


const iconUrl = (icon: string) => `/icons/${icon}`



  defineEmits(['onDetails'])





const props = defineProps({
  item: Object as PropType<PortfolioItem>,
  index: Number
});




onMounted(() => {
  gsap.registerPlugin(ScrollTrigger)
  if (process.client) {
    const selector = `.work-item-${props.index}`
    const element = document.querySelector(selector);

    const tl = gsap.timeline({
      scrollTrigger: {
        trigger: element,
        toggleActions:"restart reverse restart reset"
      },
    })
    tl.from(`${selector}`, {
      opacity: 0,
      yPercent:15,
      duration: 0.5
    })
    tl.from(`${selector} .tech-icon`,{
      xPercent:100,
      opacity:0,
      stagger:0.15
    })


  }

})
</script>

<style lang="scss">
.project {
  min-height: calc(100vh - 112px);

  @media (max-width: 992px) {
    min-height: 100vh;
  }
}
</style>
