// app/components/ReadMore.tsx
"use client";
import React, { useState, useEffect } from "react";

interface ReadMoreProps {
  text: string;
  wordsCount?: number;
  default?: boolean;
  className: string;
}

const ReadMore: React.FC<ReadMoreProps> = ({
  text,
  wordsCount = 20,
  default: defaultState = false,
  className = "",
}) => {
  const [expand, setExpand] = useState(defaultState);
  const [textLength, setTextLength] = useState<number | null>(null);

  useEffect(() => {
    setTextLength(text?.split(" ").length ?? 0);
  }, [text]);

  return (
    <p className={`transition-all ${className}`}>
      {expand || textLength! <= wordsCount
        ? text
        : text?.split(" ").slice(0, wordsCount).join(" ") + " ... "}
      {text && text.split(" ").length > wordsCount && (
        <button
          className={
            "text-xl hover:bg-white underline border-primary transition hover:bg-opacity-10 p-1 rounded-lg"
          }
          onClick={() => setExpand(!expand)}
        >
          {expand ? "Read Less" : "Read More"}
        </button>
      )}
    </p>
  );
};

export default ReadMore;

// components/ReadMore.vue
<script setup lang='ts' >

const props = defineProps({
    text: String,
    wordsCount: {
        type: Number,
        default: 20,
    },
    default: {
        type: Boolean,
        default: false,
    }

})

const textLength = computed(() => props.text?.split(' ').length ?? 0)
const expand = ref(props.default);
</script> 


<template>
    <p class="transition-all">
        {{ expand || textLength <= wordsCount ? text : text?.split(' ').slice(0, wordsCount).join(' ') + ' ... ' }} <button
            v-if="text && text.split(' ').length > wordsCount"
            class=" text-xl hover:bg-white underline border-primary transition hover:bg-opacity-10 p-1 rounded-lg "
            @click="expand = !expand">{{ expand?' Read Less': 'Read More' }} </button>
    </p>
</template> 
<style lang='scss'>

</style>
