// app/[locale]/portfolio/page.tsx
import LightsGenerator from '@/app/components/LightsGenerator'
import React from 'react'
import projects from '@/data/projects'
import { NextPage } from 'next'
import { type PortfolioItem as PortfolioItemType } from '@/types/PortfolioItem'
import ProjectDetails from './ProjectDetails'
import PortfolioItem from './PortfolioItem'


const page: NextPage = (props: any) => {



    let projectDetails: PortfolioItemType | undefined = projects.find(p => p.key === props.searchParams.project);



    return (
        <>
            <div className="page portfolio-page  relative z-0 flex flex-col ">
                <LightsGenerator />
                <div className="page-overlay "></div>
                
                <div className="container px-12 mx-auto">

                    <div className=" px-4 mx-auto space-y-12">
                        {projects.map((item) => <PortfolioItem item={item} key={item.id} className="items-center" data-aos-duration={1000}  >
                        </PortfolioItem>
                        )}
                    </div>
                </div>
            </div >


            <ProjectDetails project={projectDetails}></ProjectDetails>
        </>

        // <Transition name="showGallery" @enter="onEnter" @leave="onLeave">
        //     <div v-if="showGallery" :class="{ 'bg-black bg-opacity-80': showGallery }"
        //         class="gallery flex items-center justify-center h-screen w-screen z-20 transition fixed top-0 left-0">
        //         <button class="absolute right-10 top-10 z-40" @click="closeGallery">
        //             <icon class="text-5xl text-gray-300" name="solar:close-circle-linear" />
        //         </button>




        //     </div>
        // </Transition>


    )

}
export default page

// pages/Portfolio/index.vue
<template>
    <div class="page portfolio-page bg-primary bg-opacity-5">

        <div class="page-overlay  flex-grow-1 min-h-full"></div>
        <div
            class="page-lights absolute top-0 h-full flex-grow-1 overflow-x-hidden">



        </div>
        <!-- <div class="page-overlay flex-grow-1"></div> -->


        <div class="container px-4 mx-auto">
            <PortfolioItem class="items-center"
                v-for="(item, i) in projects" :key="item.id" :item="item">
            </PortfolioItem>
        </div>
    </div>
</template>


<script setup lang="ts">
import type { PortfolioItem as Project } from '@/types/PortfolioItem'

import ProjectsList from '@/data/projects.json'



const projects = ref<Project[]>()

onMounted(() => {
    projects.value = ProjectsList as Project[]
})


definePageMeta({
    layout: "default"
})
</script>
